config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "users/new"
  get "static_pages/home"
  get "static_pages/help"
  get "/signup", to: "users#new"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :followers
      get :following
    end
  end
  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "static_pages/about"
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
    @feed_items = current_user.feed if logged_in?
  end

  def help
  end
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Sample App</h1>

<p>This is about page</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Sample App</h1>
<head>
  <title>
    <%= yield(:title) %> | Ruby on Rails Tutorial Sample App
  </title>
</head>
<p>This is help page</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div>
    <aside>
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div>
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<%else%>
  <h1>Welcome to the Sample App</h1>
  <div>
    <%= link_to "Login", login_path, class: "btn btn-lg btnprimary" %>
  </div>
  <div class="center jumbotron">
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btnprimary" %>
  </div>

<% end %>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200")%>