config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "users/new"
  get "static_pages/home"
  get "static_pages/help"
  get "/signup", to: "users#new"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :followers
      get :following
    end
  end
  resources :relationships, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "static_pages/about"
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,only: [:edit,:update]
  before_action :valid_user, only:[:edit,:update]
  before_action :check_expiration, only: [:edit,:update]
  def new
  end
  def create
    @user =User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions."
      redirect_to root_path
    else
      flash.now[:danger] = "Email address not found."
      render :new,status: :unprocessable_entity
    end
  end
  def edit

  end

  def update
    if params[:user][:password].empty?
         @user.errors.add(:password, :blank)
         render :edit,status: :unprocessable_entity
    elsif @user.update(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render :edit,status: :unprocessable_entity

    end
  end

  private
  def user_params
    params.require(:user).permit(:password)
  end
  def get_user
    @user = User.find_by(email: params[:email])
  end
  def valid_user
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_path, alert: "Invalid"
    end
  end
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_password_reset_url, alert: "Password reset has expired."
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title,'Reset Password') %>
<h1> Reset password</h1>
<div>
  <div>
    <%= form_with(model: @user,url:password_reset_path(params[:id]), local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= hidden_field_tag :email,@user.email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Update Password" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title,"Forgot Password") %>

<h1>Forgot password</h1>
<div>
  <div>
    <%= form_with(url: password_resets_path, scope: :password_reset, local:true) do |f| %>
    <%= f.label :email %>
      <%= f.email_field :email,class: 'form-control' %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>